language: node_js
node_js: stable
dist: trusty
sudo: false
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
- cd application
- bower install
- polylint
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: sT0wQlr/A37Ud8A+kF7BZCgvZnrR4zfO0slyIbjNNTaf+t06lnAlSh4jYewDRHcCTZeSIe84USXX1esf3xc4reoUoQLe3EQPPqHSeBFgdmtai/eDmE2Jv9gClMfjc7mGKJ1dtqSQ3Tal9I4npQTa6ddl/Bb3Fwca2yzFxzvIJMAAIWgqSrmXS6BTz95Lsqf83H1zeD9kA4SFiE2+cque6iKQ2gLDCa/YAGNelJiwoP1WnmXRz6kYWSH4Q6ol6J+JpKzXIBOrUAyWMkBMdUyJgjb0rqSMYIT8fz1j1R1ggAjIyN+sPi1kLN+X5nBmUMmieemdmkgHecpvZjQZ487X66/ES7S1DoCfHHDED+XJqzFLkFSbyv6zPXtiwS60Rlx5L8BBO8hF1oyM8Za5arbWhe2BgT9pUejfENHqOWil42SxX0r5ZHppRkKNmEqmp3JrKpR5HkIboON5GTM7zth0NvDsZxehmKdG12KytyTXFJ/SpYCg2abUcpKeX2ql6Jtx5F9abqmWNsXoTg40aMmosfjIZj6St+DUwWkD7jhGcj/dJLWBdQGtwUPtGSvaerPfE26hwSKtDyXX6n8gJmy6f6iNVXyPr/wM2uy3XwDmn2ewa+stPtbIbkzpPx8Jb6C+mIq7dc06d6CilU21I/boRAywCQB+vkdReQcCC3g3gQA=
  - secure: n/yhjUfcqGGSugP58C6OJVAEwlyzvS5ygbTLZr+afSjfmW7mLUITczCjbd6hgoeYkNapVI4tDnTucCMEZYcC/6ReMd0IRP8Uu4ySQ2NchuTOqoQP0B+Wg9fxE1NefJk9P42su+ovTFlmFcuBqsp7xrTYVnYF2Elq7jhLQRu6OQUWi5PLM65OeiBhQEm2AyRCvGaTSr5YT4yLZNYhVyqTjI7Ce3Sl3cCm+FN3LCrZfJLw3CBkS1pGzcQBE0NZtvzzCpbkjvXprmowNL9GbuhxkRXVN/DnUsXDqDYknG1PQS9Vg+Ez4YHPE95kghqQr2WSVnHgK6bYnaqq++QX3rfbIw0YdAdJNCh9/GNpAaEY4P2X3OVR7VnCfLiCtjOXMyKVbxY0k+us9JWbMq6meS0Te7lLhtAFSaxDaTSCr2w3lV/aMzT07Lw7z8QTA+LKrvTakIQrMXYu5lJAuBXDx4zZMUflGRR/nwNgsn9bvlw/TZcAGAOtsN0Qns1lYa1zF2IWxwIqtW9i3U/u2oMKvOJYkQL53WWCU2o3Tj9UAWM1r+WAXB5gT4Ei+V22Fu7Z9GxQaruXcxSVGZYzaVgXeTPRjGQPKGbNmbbfy3m4wV8nef/uz0qJbwkp+sKTHVy/TTmAkKiYH/DpCHBDneo0s++tlBOXVQY/bVRA6P5jJojBfSI=
